microservice-chart:
  namespace: "srtp"

  image:
    repository: ghcr.io/pagopa/rtp-activator
    tag: "2.6.0"
    pullPolicy: Always

  ingress:
    host: "srtp.itn.internal.uat.cstar.pagopa.it"

  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "250m"
      memory: "512Mi"

  autoscaling:
    enable: false
#    minReplica: 1
#    maxReplica: 3
#    pollingInterval: 30
#    cooldownPeriod: 300
#    triggers:
#      - type: cpu
#        metadata:
#          type: Utilization
#          value: "60"

  envConfig:
    BASE_URL: "https://api-rtp.uat.cstar.pagopa.it/rtp/activation/activations/"
    SP_BASE_URL: "https://api-rtp.uat.cstar.pagopa.it/rtp/rtps/"
    EPC_MOCK_URL: "https://api-rtp.uat.cstar.pagopa.it/rtp/mock"
    AZURE_STORAGE_ACCOUNT_NAME: "cstaruitnsrtpsa"
    CALLBACK_BASE_URL: "https://api-rtp-cb.uat.cstar.pagopa.it/rtp/cb"

  keyvault:
    name: "cstar-u-itn-srtp-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
