microservice-chart:
  namespace: "srtp"

  image:
    repository: ghcr.io/pagopa/rtp-consumer
    tag: snapshot-main
    pullPolicy: Always


  ingress:
    host: "srtp.itn.internal.dev.cstar.pagopa.it"

  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "100Mi"
      cpu: "100m"

  autoscaling:
    enable: false
#    minReplica: 1
#    maxReplica: 3
#    pollingInterval: 30 # seconds
#    cooldownPeriod: 300 # seconds
#    triggers:
#      - type: cpu
#        metadata:
#          type: Utilization
#          value: "60"

  envConfig:
    BASE_URL: "https://api-rtp.dev.cstar.pagopa.it/rtp/consumer/"

  keyvault:
    name: "cstar-d-itn-srtp-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"

  # nodeSelector: {}

  # tolerations: []

  # affinity: {}
