microservice-chart:
  namespace: "srtp"

  image:
    repository: ghcr.io/pagopa/rtp-sender
    tag: snapshot-main
    pullPolicy: Always

  ingress:
    host: "srtp.itn.internal.uat.cstar.pagopa.it"

  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "250m"
      memory: "512Mi"

  autoscaling:
    enable: false
#    minReplica: 1
#    maxReplica: 3
#    pollingInterval: 30
#    cooldownPeriod: 300
#    triggers:
#      - type: cpu
#        metadata:
#          type: Utilization
#          value: "60"

  envConfig:
    BASE_URL: "https://api-rtp.uat.cstar.pagopa.it/rtp/activation/"
    SP_BASE_URL: "https://api-rtp.uat.cstar.pagopa.it/rtp/rtps/"
    PAYEES_REGISTRY_BASE_URL: "https://api-rtp.uat.cstar.pagopa.it/rtp/payees/"
    EPC_MOCK_URL: "https://api-rtp.uat.cstar.pagopa.it/rtp/mock"
    AZURE_STORAGE_ACCOUNT_NAME: "cstaruitnsrtpsa"
    CALLBACK_BASE_URL: "https://api-rtp-cb.uat.cstar.pagopa.it/rtp/cb"
    GDP_EVENTHUB_NAME: "pagopa-u-itn-gps-rtp-integration-evh"
    GDP_EVENTHUB_TOPIC: "rtp-events"
    GDP_EVENTHUB_CONSUMER_GROUP: "rtp-events-processor"
    REGISTRY_DATA_CACHE_TTL: "PT5M"
    PAYEES_REGISTRY_DATA_CACHE_TTL: "PT5M"
    MIL_AUTH_TOKEN_URL: "https://api-mcshared.uat.cstar.pagopa.it/auth/token"

  keyvault:
    name: "cstar-u-itn-srtp-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"

  azureFile:
    create: true
    mounts:
      - shareName: cstar-u-itn-srtp-jks-file-share
        name: share-volume
        readOnly: true

postman-test:
  run: true
  repoName: rtp-sender
  dir: postman
  collectionName: "rtp-sender-E2E.postman_collection.json"
  envVariablesFile: "rtp_uat.postman_environment.json" #inside azdo secure files